### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'status'

### ISSUE THREAD

**Issue by Pseudozoid** [yurihs/waybar-media#6]
```
Traceback (most recent call last):
  File "/home/pseudozoid/.local/bin/./waybar-media.py", line 275, in <module>
    main()
  File "/home/pseudozoid/.local/bin/./waybar-media.py", line 252, in main
    with MediaWatcher(bus, do_print_status=(arg == 'status')) as media_watcher:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pseudozoid/.local/bin/./waybar-media.py", line 104, in __init__
    self.status_builder.print_status()
  File "/home/pseudozoid/.local/bin/./waybar-media.py", line 233, in print_status
    print(self.build_status())
          ^^^^^^^^^^^^^^^^^^^
  File "/home/pseudozoid/.local/bin/./waybar-media.py", line 229, in build_status
    {'tooltip': self._build_tooltip(), 'text': self._build_text(max_width=80), 'class': self._build_classes()}
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pseudozoid/.local/bin/./waybar-media.py", line 173, in _build_tooltip
    if player.status in ['playing', 'paused']:
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status'
```

This issue still persists for me even after it was addressed earlier.  None of the arguments are working and I always get this error when I try to execute the waybar-media.py manually.

**Comment by notSYNKR** [comment]
Does anyone have any workarounds for this, it seems that this issue still persists
